### ISSUE TITLE
Unable to install extension from xpi file:  VimFx@akhodakivskiy.github.com is missing bootstrap method startup

### ISSUE THREAD

**Issue by erjoalgo** [akhodakivskiy/VimFx#504]
Hi, 

I'm trying to install the extension from the xpi file, and I get this:

1434039185130	addons.xpi	WARN	Error loading bootstrap.js for VimFx@akhodakivskiy.github.com: Error opening input stream (invalid filename?)
1434039185132	addons.xpi	WARN	Add-on VimFx@akhodakivskiy.github.com is missing bootstrap method startup

I noticed that the bootstrap.js defines a "startup" function in a weird way:

    global.startup = function(data, reason) {

Is this an issue of incompatibility with my browser version? I'm using Iceweasel 31.4.0 and VimFx 0.5.17

**Comment by akhodakivskiy** [comment]
How did you get the XPI file? Did you build it yourself?

**Comment by erjoalgo** [comment]
yes. I pulled from the upstream and zipped it, then "install from file" from firefox. I think this has worked in the past.

I tried with the latest firefox, and still get the same problem:

1434047215925	addons.xpi	WARN	Error loading bootstrap.js for VimFx@akhodakivskiy.github.com: Error opening input stream (invalid filename?): jar:file:///home/ealfonso/.mozilla/firefox/8l2rgplb.default/extensions/VimFx@akhodakivskiy.github.com.xpi!/bootstrap.js1434047215926	addons.xpi	WARN	Add-on VimFx@akhodakivskiy.github.com is missing bootstrap method install1434047215973	addons.xpi	WARN	Add-on VimFx@akhodakivskiy.github.com is missing bootstrap method startup1434047237224	addons.xpi	WARN	Add-on VimFx@akhodakivskiy.github.com is missing bootstrap method shutdown

**Comment by lydell** [comment]
> I noticed that the bootstrap.js defines a "startup" function in a weird way:

That's not a weird way.

> I'm using VimFx 0.5.17

You're probably not if you've built the xpi yourself.

Anyhow, the error message you get means that a `require`d file couldn't be found, which makes the extension crash before it gets the chance to define the install method.

I'd suggest building from the develop branch instead. It's easier.

**Comment by erjoalgo** [comment]
I git cloned from the develop branch at https://github.com/akhodakivskiy/VimFx.git, then zipped to xpi and tried to 'install from file' from firefox. I get "cannot install addon because it seems to be corrupt", and this on the traceback:

1434062163446	addons.xpi	WARN	Invalid XPI: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIZipReader.getInputStream]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadManifestFromZipReader :: line 1021"  data: no] Stack trace: loadManifestFromZipReader()@resource://gre/modules/addons/XPIProvider.jsm:1021 < AI_loadManifest()@resource://gre/modules/addons/XPIProvider.jsm:5079 < AI_initLocalInstall()@resource://gre/modules/addons/XPIProvider.jsm:4687 < AI_createInstall()@resource://gre/modules/addons/XPIProvider.jsm:5691 < XPI_getInstallForFile()@resource://gre/modules/addons/XPIProvider.jsm:3601 < callProvider()@resource://gre/modules/AddonManager.jsm:192 < getInstallForFile_nextObject()@resource://gre/modules/AddonManager.jsm:1639 < AOC_callNext()@resource://gre/modules/AddonManager.jsm:267 < AsyncObjectCaller()@resource://gre/modules/AddonManager.jsm:247 < AMI_getInstallForFile()@resource://gre/modules/AddonManager.jsm:1647 < AM_getInstallForFile()@resource://gre/modules/AddonManager.jsm:2625 < buildNextInstall()@extensions.js:1219 < cmd_installFromFile_doCommand()@extensions.js:1225 < gVC_doCommand()@extensions.js:1365 < initialize/<()@extensions.js:94 < <file:unknown>

1434062163659	addons.xpi	WARN	Download of file:///home/user/.mozilla/firefox/8l2rgplb.default/extensions/VimFx.xpi failed: [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIZipReader.getInputStream]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadManifestFromZipReader :: line 1021"  data: no] Stack trace: loadManifestFromZipReader()@resource://gre/modules/addons/XPIProvider.jsm:1021 < AI_loadManifest()@resource://gre/modules/addons/XPIProvider.jsm:5079 < AI_onStopRequest()@resource://gre/modules/addons/XPIProvider.jsm:5325 < <file:unknown>


What is going on? I'm pretty sure that the xpi file exists. I will try with the latest firefox

**Comment by akhodakivskiy** [comment]
Did you build the script before zipping it? This extension is written in coffeescript, so it needs to be translated to javascript before packing it into XPI. The develop branch uses Gulp.

**Comment by erjoalgo** [comment]
Do you have any instructions with gulp? Why is the installation trying to make some connection? 

ealfonso-netbook$gulp
[19:52:15] Requiring external module coffee-script/register
[19:52:19] Using gulpfile ~/repos/vimfx3/VimFx/gulpfile.coffee
[19:52:19] Starting 'build'...
[19:52:19] Starting 'clean'...
[19:52:20] Finished 'clean' after 139 ms
[19:52:20] Starting 'copy'...
[19:52:20] Starting 'node_modules'...
[19:52:20] Starting 'coffee'...
[19:52:20] Starting 'chrome.manifest'...
[19:52:20] Starting 'install.rdf'...
[19:52:21] Finished 'chrome.manifest' after 1.38 s
[19:52:21] Finished 'install.rdf' after 1.37 s
[19:52:25] Finished 'node_modules' after 5.76 s
[19:52:25] Starting 'require-data'...
[19:52:26] Finished 'require-data' after 207 ms
[19:52:26] Starting 'templates'...
[19:52:26] Finished 'templates' after 35 μs
[19:52:27] Finished 'coffee' after 7.75 s
[19:52:28] Finished 'copy' after 7.96 s
[19:52:28] Finished 'build' after 8.15 s
[19:52:28] Starting 'xpi'...
[19:52:28] Finished 'xpi' after 427 ms
[19:52:28] Starting 'push'...
[19:52:28] 'push' errored after 90 ms
[19:52:28] Error: connect ECONNREFUSED
  at exports._errnoException (util.js:746:11)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

**Comment by mozillazg** [comment]
@erjoalgo Build with `gulp xpi`:
```
$ gulp xpi
[09:37:25] Requiring external module coffee-script/register
[09:37:27] Using gulpfile ~/VimFx/gulpfile.coffee
[09:37:27] Starting 'build'...
[09:37:27] Starting 'clean'...
[09:37:27] Finished 'clean' after 23 ms
[09:37:27] Starting 'copy'...
[09:37:27] Starting 'node_modules'...
[09:37:27] Starting 'coffee'...
[09:37:27] Starting 'chrome.manifest'...
[09:37:27] Starting 'install.rdf'...
[09:37:27] Finished 'chrome.manifest' after 211 ms
[09:37:27] Finished 'install.rdf' after 205 ms
[09:37:28] Finished 'node_modules' after 672 ms
[09:37:28] Starting 'require-data'...
[09:37:28] Finished 'require-data' after 98 ms
[09:37:28] Starting 'templates'...
[09:37:28] Finished 'templates' after 6.56 μs
[09:37:28] Finished 'coffee' after 1.04 s
[09:37:28] Finished 'copy' after 1.12 s
[09:37:28] Finished 'build' after 1.14 s
[09:37:28] Starting 'xpi'...
[09:37:28] Finished 'xpi' after 81 ms

$ ls -l build/*.xpi
-rw-r--r--  1 xxx  staff  307668  6 12 09:37 build/VimFx.xpi
```

**Comment by erjoalgo** [comment]
Thanks. I was able to install it on the latest firefox. I wasn't able to install it on the latest iceweasel which is version ~31.

**Comment by lydell** [comment]
@erjoalgo have a look at CONTRIBUTING-CODE.md next time. The different gulp tasks are documented there.

The latest development version requires Firefox 38 or later, so that's why it's not working on Iceweasel 31.

**Comment by jonpolak** [comment]
vimFx works on Firefox 38.2 but not on Iceweasel 38.4 both installed on my system. 

What version of vimFX is compatible with latest iceweasel 38.4 ?
