### ISSUE TITLE
Compile problem since 0.5.14 with CoffeeScript 1.4.0 from Debian testing

### ISSUE THREAD

**Issue by dalb8** [akhodakivskiy/VimFx#511]
I get an error:
```
Performing clean…
Generating js files…
Error: In extension/packages/commands.coffee, Parse error on line 325: Unexpected 'INDENT'
    at Object.parseError (/usr/lib/coffee-script/lib/coffee-script/parser.js:477:11)
    at Object.parse (/usr/lib/coffee-script/lib/coffee-script/parser.js:554:22)
    at Object.exports.compile.compile (/usr/lib/coffee-script/lib/coffee-script/coffee-script.js:47:20)
    at compileScript (/usr/lib/coffee-script/lib/coffee-script/command.js:182:33)
    at /usr/lib/coffee-script/lib/coffee-script/command.js:152:18
    at fs.js:268:14
    at Object.oncomplete (fs.js:107:15)
make: *** [extension/bootstrap.js] Error 1
```

Sorry I don't know anything about Java/Coffee.

**Comment by lydell** [comment]
#443
