### ISSUE TITLE
`encodeURI` breaks loading of the public API when there are already encoded spaces in the URL

### ISSUE THREAD

**Issue by lazywei** [akhodakivskiy/VimFx#516]
Hi,

I'm trying to install VimFx from source.
I pull the latest develop branch, and `npm install` for dependencies. After that, I run `npm run gulp -- xpi` to build the xpi file. Finally, I drag the VimFx.xpi to my Firefox for installation.

However, it seems the hjkl and other features are not working any more. I'm not sure if I missed anything.

Thanks

**Comment by lydell** [comment]
You seem to have done everything right. Does _anything_ work?

**Comment by lazywei** [comment]
The `/` brings the search box, though I'm not sure if it is Firefox's built-in functionality.
Do you think I can try any other functions?
Thanks

**Comment by lazywei** [comment]
- Though `/` brings searching box, neither `n` nor `N` wors.
- `space` and `shift-space` also works.

**Comment by lydell** [comment]
Does VimFx show up in the Add-ons Manager? Does VimFx's settings show up in the Add-ons Manager? Does VimFx's button show up (or can it be added by customizing your toolbars)? What happens if you click it? Can you show VimFx's help/keyboard shortcuts dialog?

If you get the button you could hover it after pressing `/`. If the tooltip doesn't say that you're in find mode then `/` has invoked Firefox's built-in shortcut.

**Comment by lazywei** [comment]
1. Yes, VimFx is in Add-ons Manager. However, after click "settings", I get this page without any place for doing real settings
![2015-07-04 22 36 03](https://cloud.githubusercontent.com/assets/2840571/8508292/2bba9fb0-229d-11e5-9533-8ff24fd40724.png)
2. VimFx's button doesn't show up. I can't find it from customizing toolbars either.

**Comment by lydell** [comment]
Could you check the browser console (note: _browser_ console, not web console) for VimFx errors? At this point it might be crowded with all sorts of errors and warnings making it difficult to find the VimFx related ones. Restarting Firefox helps in that case.

**Comment by lazywei** [comment]
I'm not sure if all these are related to VimFx, I paste them on anyway

```
GET https://self-repair.mozilla.org/zh-TW/repair/index.js [HTTP/1.1 404 Not Found 7ms]

Could not read chrome manifest 'file:///Applications/Firefox.app/Contents/Resources/chrome.manifest'.

JavaScript 1.7's let blocks are deprecated bootstrap.js:142:69

JavaScript 1.7's let blocks are deprecated bootstrap.js:184:32

JavaScript 1.7's let blocks are deprecated l10n.js:52:47

1436021071980	addons.xpi	WARN	Exception running bootstrap method startup on 
VimFx@akhodakivskiy.github.com: [Exception... "Component returned failure code: 0x80520012 
(NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]"  nsresult: "0x80520012 
(NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons
/XPIProvider.jsm -> jar:file:///Users/lazywei/Library/Application%20Support/Firefox/Profiles
/3bchj5is.default/extensions/VimFx@akhodakivskiy.github.com.xpi!/bootstrap.js -> jar:file:///Users
/lazywei/Library/Application%20Support/Firefox/Profiles/3bchj5is.default/extensions
/VimFx@akhodakivskiy.github.com.xpi!/lib/main.js :: module.exports :: line 68"  data: no] Stack trace: 
module.exports()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/lazywei/Library
/Application%20Support/Firefox/Profiles/3bchj5is.default/extensions
/VimFx@akhodakivskiy.github.com.xpi!/bootstrap.js -> jar:file:///Users/lazywei/Library
/Application%20Support/Firefox/Profiles/3bchj5is.default/extensions
/VimFx@akhodakivskiy.github.com.xpi!/lib/main.js:68 < XPI_callBootstrapMethod()@resource://gre
/modules/addons/XPIProvider.jsm:4451 < XPI_startup()@resource://gre/modules/addons
/XPIProvider.jsm:2168 < callProvider()@resource://gre/modules/AddonManager.jsm:208 < 
_startProvider()@resource://gre/modules/AddonManager.jsm:670 < AMI_startup()@resource://gre
/modules/AddonManager.jsm:841 < AMP_startup()@resource://gre/modules/AddonManager.jsm:2499 
< AMC_observe()@resource://gre/components/addonManager.js:55 < <file:unknown>

Could not read chrome manifest 'file:///Applications/Firefox.app/Contents/Resources/browser/extensions/%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D/chrome.manifest'.

"DEPRECATED: Module 'sdk/page-mod/match-pattern' is deprecated use 'sdk/util/match-pattern' instead
Traceback (most recent call last):
  File "resource://gre/modules/Promise-backend.js", line 867, in Handler.prototype.process
    nextValue = this.onResolve.call(undefined, nextValue);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 86, in startup/</<
    run(options);
  File "resource://gre/modules/commonjs/sdk/addon/runner.js", line 145, in run
    let program = main(options.loader, options.main);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 740, in main
    return loader.load(loader, module).exports;
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 79, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 332, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 280, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://rapportive-at-rapportive-dot-com/rapportive-amo/lib/main.js", line 3, in null
    var { MatchPattern } = require("match-pattern");
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 625, in require
    freeze(load(loader, module));
  File "resource://gre/modules/commonjs/sdk/loader/cuddlefish.js", line 79, in CuddlefishLoader/options<.load
    result = load(loader, module);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 332, in load
    evaluate(sandbox, module.uri);
  File "resource://gre/modules/commonjs/toolkit/loader.js", line 280, in evaluate
    : loadSubScript(uri, sandbox, encoding);
  File "resource://gre/modules/commonjs/sdk/page-mod/match-pattern.js", line 8, in null
    deprecateUsage("Module 'sdk/page-mod/match-pattern' is deprecated use 'sdk/util/match-pattern' instead");
  File "resource://gre/modules/commonjs/sdk/util/deprecate.js", line 18, in deprecateUsage
    let stack = get().slice(2);"
```

**Comment by lydell** [comment]
Th error is that a file seems to be missing. Unfortunately, such errors are always a bit cryptic and doesn't really tell _which_ file is missing.

Do you any programming, or did you install from source just to try the latest version?

**Comment by lazywei** [comment]
No. I build xpi immediately after cloning this repo from GitHub. I just want to try the latest version.

**Comment by lydell** [comment]
Ok, the only guess I have right now is that the public API fails to load. Could you try removing [these lines](https://github.com/akhodakivskiy/VimFx/blob/a52c090560613f2d04cfddba29dffa744fd62f75/extension/lib/main.coffee#L47-54) and then install again? If it doesn't seem to help, please check the browser console again.

**Comment by lazywei** [comment]
Wow, it works! And no more errors in browser console.

**Comment by lydell** [comment]
Cool! You use a mac, right? It might be that you're the first mac user who tries VimFx since the public API was added and this might be a mac specific issue. I don't have a mac to test on, though, so could you do me a huge favor and try the following: Add back the code you removed and then only remove the word `encodeURI` in it and see if it works?

**Comment by lazywei** [comment]
Yes. I'm using mac :smile: 
I removed `encodeURI`, and I think it is still working.

**Comment by lydell** [comment]
Thanks, that helps a lot! Now, just one more thing: Could you go to about:config and report the value of `extensions.VimFx.api_url`?

**Comment by lazywei** [comment]
I just ran away from my laptop. Will do it tomorrow, sorry about that 😊



-- Chih-Wei (Bert)

**Comment by lydell** [comment]
Ok!

Note to self: Load un-encoded URL, add `decodeURI` to API docs.

**Comment by LazerPanther** [comment]
Same issues as @lazywei. 
With a brand new profile, 0 addons besides Extension Auto Installer, no preferences or settings changed in Firefox at all, errors on startup at the default FirefoxDeveloperEdition about:home :

```
Could not read chrome manifest 'file:///Applications/FirefoxDeveloperEdition.app/Contents/Resources/chrome.manifest'.
1436031994835	addons.xpi	WARN	Exception running bootstrap method startup on VimFx@akhodakivskiy.github.com: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/grimmjaw/Library/Application%20Support/Firefox/Profiles/olqiml41.VimFX-github/extensions/VimFx@akhodakivskiy.github.com.xpi!/bootstrap.js -> jar:file:///Users/grimmjaw/Library/Application%20Support/Firefox/Profiles/olqiml41.VimFX-github/extensions/VimFx@akhodakivskiy.github.com.xpi!/lib/main.js :: module.exports :: line 68"  data: no] Stack trace: module.exports()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/grimmjaw/Library/Application%20Support/Firefox/Profiles/olqiml41.VimFX-github/extensions/VimFx@akhodakivskiy.github.com.xpi!/bootstrap.js -> jar:file:///Users/grimmjaw/Library/Application%20Support/Firefox/Profiles/olqiml41.VimFX-github/extensions/VimFx@akhodakivskiy.github.com.xpi!/lib/main.js:68 < XPI_callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4654 < XPI_startup()@resource://gre/modules/addons/XPIProvider.jsm:2375 < callProvider()@resource://gre/modules/AddonManager.jsm:221 < _startProvider()@resource://gre/modules/AddonManager.jsm:703 < AMI_startup()@resource://gre/modules/AddonManager.jsm:874 < AMP_startup()@resource://gre/modules/AddonManager.jsm:2514 < AMC_observe()@resource://gre/components/addonManager.js:55 < <file:unknown>
Get a connection to permissions.sqlite.
OpenGL compositor Initialized Succesfully.
Version: 2.1 NVIDIA-10.4.2 310.41.35f01
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 750M OpenGL Engine
FBO Texture Target: TEXTURE_2D
1436032005782	Services.HealthReport.HealthReporter	WARN	Saved state file does not exist.
```
`Firefox Developer Edition 41.0a2 (2015-07-04)`

/> `uname -a`
/> `Darwin OSX-Grimm.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin`

Fresh clone and build on the develop branch via:
/> `cd ~/github`
/> `git clone -b develop https://github.com/akhodakivskiy/VimFx.git`
/> `cd VimFX/`
/> `nvm current`
`v0.12.5`
/> `npm install`
/> `npm update`
/> `gulp`
```
[13:00:23] Using gulpfile ~/github/VimFx/gulpfile.js
[13:00:23] Starting 'build'...
[13:00:23] Starting 'clean'...
[13:00:23] Finished 'clean' after 9.81 ms
[13:00:23] Starting 'copy'...
[13:00:23] Starting 'node_modules'...
[13:00:23] Starting 'coffee'...
[13:00:23] Starting 'chrome.manifest'...
[13:00:23] Starting 'install.rdf'...
[13:00:23] Finished 'install.rdf' after 119 ms
[13:00:23] Finished 'chrome.manifest' after 122 ms
[13:00:23] Finished 'node_modules' after 378 ms
[13:00:23] Starting 'require-data'...
[13:00:23] Finished 'require-data' after 47 ms
[13:00:23] Starting 'templates'...
[13:00:23] Finished 'templates' after 4.08 μs
[13:00:23] Finished 'coffee' after 658 ms
[13:00:23] Finished 'copy' after 684 ms
[13:00:23] Finished 'build' after 697 ms
[13:00:23] Starting 'xpi'...
[13:00:23] Finished 'xpi' after 43 ms
[13:00:23] Starting 'push'...
[13:00:23] Finished 'push' after 11 ms
[13:00:23] Starting 'default'...
[13:00:23] Finished 'default' after 2.48 μs
```
Testing your diff you [posted above](https://github.com/akhodakivskiy/VimFx/blob/a52c090560613f2d04cfddba29dffa744fd62f75/extension/lib/main.coffee#L47-54).
Will post back with results shortly.

**Comment by LazerPanther** [comment]
/> `cd ~/github/VimFx/extension/lib/`
/> `nvim main.coffee`
Comment lines 50-54 by inserting `#` at BOL.
/> `cd ...`
/> `gulp`
```
[13:12:22] Using gulpfile ~/github/VimFx/gulpfile.js
[13:12:22] Starting 'build'...
[13:12:22] Starting 'clean'...
[13:12:22] Finished 'clean' after 10 ms
[13:12:22] Starting 'copy'...
[13:12:22] Starting 'node_modules'...
[13:12:22] Starting 'coffee'...
[13:12:22] Starting 'chrome.manifest'...
[13:12:22] Starting 'install.rdf'...
[13:12:22] Finished 'install.rdf' after 114 ms
[13:12:22] Finished 'chrome.manifest' after 117 ms
[13:12:23] Finished 'node_modules' after 377 ms
[13:12:23] Starting 'require-data'...
[13:12:23] Finished 'require-data' after 47 ms
[13:12:23] Starting 'templates'...
[13:12:23] Finished 'templates' after 3.87 μs
[13:12:23] Finished 'coffee' after 651 ms
[13:12:23] Finished 'copy' after 679 ms
[13:12:23] Finished 'build' after 692 ms
[13:12:23] Starting 'xpi'...
[13:12:23] Finished 'xpi' after 42 ms
[13:12:23] Starting 'push'...
[13:12:23] Finished 'push' after 12 ms
[13:12:23] Starting 'default'...
[13:12:23] Finished 'default' after 2.59 μs
```
Open FirefoxDeveloperEdition.app
Cmd+Shift+J to open Browser Console.
No errors reported on startup.

Everything works again. Thanks for the fix!  :+1:

**Comment by LazerPanther** [comment]
Also, went back to VimFx/extensions/lib/main.coffee in nvim and uncommented lines 50-54, then deleted:
`encodeURI` on line 50.
```
47|    # Setup the public API. The URL is encoded (which means that there will be
48|    # only ASCII characters) so that the pref can be read using a simple
49|    # `Services.prefs.getCharPref()` (which only supports ASCII characters).
50|    api_url = ("#{ data.resourceURI.spec }lib/public.js")
51|    { setAPI } = Cu.import(api_url, {})
52|    setAPI(createAPI(vimfx))
53|    module.onShutdown(-> Cu.unload(api_url))
54|    prefs.set('api_url', api_url)
55|
56|    test?(vimfx)
```
/> `cd ...`
/> `gulp`
```
[13:30:32] Using gulpfile ~/github/VimFx/gulpfile.js
[13:30:32] Starting 'build'...
[13:30:32] Starting 'clean'...
[13:30:32] Finished 'clean' after 9.48 ms
[13:30:32] Starting 'copy'...
[13:30:32] Starting 'node_modules'...
[13:30:32] Starting 'coffee'...
[13:30:32] Starting 'chrome.manifest'...
[13:30:32] Starting 'install.rdf'...
[13:30:32] Finished 'chrome.manifest' after 132 ms
[13:30:32] Finished 'install.rdf' after 130 ms
[13:30:33] Finished 'node_modules' after 377 ms
[13:30:33] Starting 'require-data'...
[13:30:33] Finished 'require-data' after 63 ms
[13:30:33] Starting 'templates'...
[13:30:33] Finished 'templates' after 3.48 μs
[13:30:33] Finished 'coffee' after 656 ms
[13:30:33] Finished 'copy' after 683 ms
[13:30:33] Finished 'build' after 695 ms
[13:30:33] Starting 'xpi'...
[13:30:33] Finished 'xpi' after 43 ms
[13:30:33] Starting 'push'...
[13:30:33] Finished 'push' after 11 ms
[13:30:33] Starting 'default'...
[13:30:33] Finished 'default' after 2.38 μs
```
Opened FirefoxDeveloperEdition.app
Cmd+Shift+J
No reported errors.

Hit `t` for new tab, `about:config` and search for VimFx.api:
Preference Name
**`extensions.VimFx.api_url`**
Status
**`user set`**
Value
**`jar:file:///Users/grimmjaw/Library/Application%20Support/Firefox/Profiles/olqiml41.VimFX-github/extensions/VimFx@akhodakivskiy.github.com.xpi!/lib/public.js`**

Nothing seems different except the api value is showing in about:config now.

**Comment by lydell** [comment]
Thanks @LazerPanther! That api_url shows that the issue might bot be mac-specific at all, it is more likely about there being a space in the url, encoded as %20. This should be easy to fix.

**Comment by Spittie** [comment]
Hi,

Same problem here on Arch Linux, but I can't reproduce on Windows 8.1. Both running Firefox 39.
My ```api_url``` has a ```%2520``` tho, almost as if it was encoded two times: ```jar:file:///home/spittie/.mozilla/firefox/mktqcusc.Default%2520User/extensions/VimFx@akhodakivskiy.github.com.xpi!/lib/public.js```

This probably isn't the best way to deal with this, but just adding ```api_url = api_url.replace('%2520', ' ')``` right after https://github.com/akhodakivskiy/VimFx/blob/develop/extension/lib/main.coffee#L50 fixes this for me.

**Comment by lydell** [comment]
> My api_url has a %2520 tho, almost as if it was encoded two times

Yes, it has been encoded twice. That's the problem. We should stop encoding it and use a complex string pref instead.
